import {verifyAccessIdentity,assertRequestSecurity,responseHeaders,redact} from "./security.js";
import {OperationalError,safeError} from "./errors.js";
import {D1AssetMetadataStore} from "../storage/assets.js";
import {R2ArtworkStore} from "../storage/artwork.js";
import {AssetManager} from "../assets/manager.js";
const json=(value,status=200,extra={})=>new Response(JSON.stringify(value),{status,headers:{...responseHeaders,...extra}});
const parseJson=async request=>{if(!(request.headers.get("Content-Type")||"").toLowerCase().startsWith("application/json"))throw new OperationalError("UNSUPPORTED_MEDIA_TYPE","Send JSON requests only.",{status:415});const text=await request.text();if(text.length>20000)throw new OperationalError("REQUEST_TOO_LARGE","The request is too large.",{status:413});try{return JSON.parse(text)}catch{throw new OperationalError("INVALID_JSON","The request is not valid JSON.")}};
const parseForm=async request=>{const type=request.headers.get("Content-Type")||"";if(!type.toLowerCase().startsWith("multipart/form-data"))throw new OperationalError("UNSUPPORTED_MEDIA_TYPE","Upload images using multipart form data.",{status:415});const length=Number(request.headers.get("Content-Length")||0);if(length>11*1024*1024)throw new OperationalError("REQUEST_TOO_LARGE","The upload exceeds the 10 MB image limit.",{status:413});return request.formData()};
const makeAssets=(env,repository)=>new AssetManager({repository,metadata:new D1AssetMetadataStore(env.PUBLICATIONS_DB),objects:new R2ArtworkStore(env.ARTWORK_BUCKET)});
async function handleAssets(request,path,url,manager){
 if(request.method==="GET"&&path==="assets"){const communicationId=url.searchParams.get("communicationId");return json({assets:await manager.list(communicationId)})}
 const match=path.match(/^assets\/(AST-(?:\d{3}|[A-F0-9]{12}))(?:\/(replace))?$/);
 if(request.method==="GET"&&match&&!match[2])return json({asset:await manager.get(match[1])});
 if(request.method==="POST"&&path==="assets/upload"){const form=await parseForm(request);const result=await manager.upload({communicationId:String(form.get("communicationId")||""),file:form.get("file"),altText:String(form.get("altText")||"")});return json(result,result.duplicate?200:201)}
 if(request.method==="PATCH"&&match&&!match[2])return json({asset:await manager.update(match[1],await parseJson(request))});
 if(request.method==="POST"&&match?.[2]){const form=await parseForm(request);return json(await manager.replace(match[1],{file:form.get("file"),confirmPublished:form.get("confirmPublished")==="true"}))}
 if(request.method==="DELETE"&&match&&!match[2])return json(await manager.remove(match[1],{confirmPublished:url.searchParams.get("confirmPublished")==="true"}));
 throw new OperationalError("NOT_FOUND","The image endpoint was not found.",{status:404,recovery:"Return to Images."})
}
export async function handleApi(request,env,repository,{fetchImpl=fetch,assetManager}={}){const correlationId=request.headers.get("X-Correlation-ID")?.match(/^[a-zA-Z0-9-]{8,80}$/)?.[0]||crypto.randomUUID();try{assertRequestSecurity(request,["GET","POST","PATCH","DELETE"]);await verifyAccessIdentity(request,env,{fetchImpl});const url=new URL(request.url),path=url.pathname.replace(/^\/communications\/api\/?/,"");if(request.method==="GET"&&path==="health")return json({status:"protected",storage:Boolean(env.PUBLICATIONS_DB)?"configured":"not configured",artwork:Boolean(env.ARTWORK_BUCKET)?"configured":"not configured",checkedAt:new Date().toISOString()});const assets=assetManager||makeAssets(env,repository);if(path==="assets"||path.startsWith("assets/"))return handleAssets(request,path,url,assets);throw new OperationalError("NOT_FOUND","The endpoint was not found.",{status:404,recovery:"Return to the SMCU Image Library."})}catch(error){const safe=safeError(error);console.error(JSON.stringify(redact({level:"error",correlationId,code:safe.code,path:new URL(request.url).pathname})));return json({error:safe,correlationId},safe.status||500,{Allow:"GET, POST, PATCH, DELETE"})}}
