import { OperationalError, safeError } from "./errors.js";
const DESTINATIONS=new Set(["shopify","instagram","facebook"]), ACTIONS=new Set(["publish","schedule","draft"]);
const stable=async value=>Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value)))).map(x=>x.toString(16).padStart(2,"0")).join("");
function baseRecord(repository,id){const document=repository.documents.find(d=>d.id===id);if(!document)throw new OperationalError("COMMUNICATION_NOT_FOUND","The communication was not found.",{status:404,recovery:"Return to Publishing and choose an existing communication."});return {document,campaign:document.campaignId?repository.campaigns.find(c=>c.id===document.campaignId):null};}
function readiness({document,assets},body,now){const reasons=[];if(!["Approved","Published","Scheduled"].includes(document.status))reasons.push("Communication is not approved.");if(!document.summary?.trim())reasons.push("Content is missing.");if(!assets.length)reasons.push("Required artwork is missing.");if(assets.length&&!assets.some(a=>a.primary))reasons.push("Select primary artwork.");if(assets.some(a=>!a.altText?.trim()))reasons.push("Add alt text to every image.");if(assets.some(a=>!a.url||!a.mimeType?.startsWith("image/")||!a.width||!a.height))reasons.push("Artwork metadata is incomplete.");if(body.modifiedDate!==document.modifiedDate)reasons.push("Communication changed after this publishing view was opened.");if(body.action==="schedule"&&(!body.scheduledTime||Number.isNaN(Date.parse(body.scheduledTime))||Date.parse(body.scheduledTime)<=now().getTime()))reasons.push("Schedule must be a valid future time.");return reasons;}
function validate(body,{confirm=false}={}){if(!body||typeof body!=="object"||Array.isArray(body))throw new OperationalError("INVALID_REQUEST","The publishing request is invalid.");if(!/^[A-Z]{2}-\d{3}$/.test(body.communicationId||""))throw new OperationalError("INVALID_COMMUNICATION","Choose a valid communication.");if(!ACTIONS.has(body.action))throw new OperationalError("INVALID_ACTION","Choose publish, schedule, or draft.");if(!Array.isArray(body.destinations)||!body.destinations.length||body.destinations.some(x=>!DESTINATIONS.has(x))||new Set(body.destinations).size!==body.destinations.length)throw new OperationalError("INVALID_DESTINATIONS","Choose one or more available destinations.");if(confirm&&body.confirmed!==true)throw new OperationalError("CONFIRMATION_REQUIRED","Confirm the exact destinations before publishing.");if(typeof body.modifiedDate!=="string")throw new OperationalError("STALE_DATA","Refresh the communication before publishing.");if(body.idempotencyKey&&!/^[a-f0-9-]{16,128}$/i.test(body.idempotencyKey))throw new OperationalError("INVALID_IDEMPOTENCY_KEY","Refresh Publishing and confirm again.");if(body.action==="draft"&&(body.destinations.length!==1||body.destinations[0]!=="shopify"))throw new OperationalError("INVALID_DESTINATIONS","Drafts can be created in Shopify only.");if(body.action==="schedule"&&body.destinations.includes("shopify"))throw new OperationalError("INVALID_DESTINATIONS","Shopify scheduling is not enabled. Schedule social channels through Buffer.");return {...body,destinations:[...body.destinations].sort()};}
export class PublishingOrchestrator{
 constructor({repository,store,shopify,buffer,assetResolver,clock=()=>new Date()}){Object.assign(this,{repository,store,shopify,buffer,assetResolver,clock});}
 async getRecord(id){const record=baseRecord(this.repository,id);record.assets=this.assetResolver?await this.assetResolver(id):record.document.assets.map(assetId=>this.repository.assets.find(a=>a.id===assetId)).filter(Boolean).map((a,index)=>({...a,primary:index===0,mimeType:`image/${a.format?.toLowerCase()}`,width:a.dimensions?.width,height:a.dimensions?.height}));return record;}
 async preview(input){const body=validate(input),record=await this.getRecord(body.communicationId),reasons=readiness(record,body,this.clock);return {communication:{id:record.document.id,title:record.document.title,modifiedDate:record.document.modifiedDate},campaign:record.campaign?{id:record.campaign.id,title:record.campaign.title}:null,assets:record.assets.map(a=>({id:a.id,title:a.title,url:a.url,altText:a.altText,primary:a.primary})),destinations:body.destinations,action:body.action,scheduledTime:body.scheduledTime||null,ready:!reasons.length,reasons};}
 async execute(input,{correlationId=crypto.randomUUID(),retryFailed=false}={}){const body=validate(input,{confirm:true}),preview=await this.preview(body);if(!preview.ready)throw new OperationalError("NOT_READY",preview.reasons.join(" "),{status:422,recovery:"Resolve the listed publishing blockers, then try again."});const record=await this.getRecord(body.communicationId),fingerprint=await stable(JSON.stringify({id:body.communicationId,modified:body.modifiedDate,action:body.action,schedule:body.scheduledTime||null,destinations:body.destinations})),key=body.idempotencyKey||fingerprint,results=[];
  for(const destination of body.destinations){let stored=await this.store.reserve({communicationId:record.document.id,campaignId:record.campaign?.id,destination,requestedAction:body.action,idempotencyKey:key,scheduledTime:body.scheduledTime,requestFingerprint:fingerprint,correlationId});if(stored.request_fingerprint!==fingerprint)throw new OperationalError("IDEMPOTENCY_CONFLICT","This publishing key belongs to a different request.",{status:409,recovery:"Refresh Publishing and confirm again."});if(["published","scheduled","pending","draft"].includes(stored.status)&&stored.attempt_count>0){results.push(toResult(stored,true));continue}if(stored.status==="failed"&&!retryFailed){results.push(toResult(stored,true));continue}
   try{const result=destination==="shopify"?await this.shopify.publish({document:record.document,assets:record.assets,publish:body.action!=="draft"}):await this.buffer.publish({destination,document:record.document,assets:record.assets,scheduledTime:body.action==="schedule"?body.scheduledTime:null});stored=await this.store.complete(key,destination,result);results.push(toResult(stored,false));}catch(error){const safe=safeError(error);stored=await this.store.fail(key,destination,safe);results.push({...toResult(stored,false),message:safe.message,retryable:safe.retryable});}
  }return {communicationId:record.document.id,idempotencyKey:key,correlationId,results};}
}
function toResult(row,reused){return {destination:row.destination,status:row.status,externalId:row.external_platform_id,externalUrl:row.external_url,failureCode:row.failure_code,recovery:row.recovery_message,attemptCount:row.attempt_count,reused};}
