import { OperationalError } from "../core/errors.js";
import { requestJson } from "./http.js";
const ORGS=`query DeskOrganizations { account { organizations { id name } } }`;
const CHANNELS=`query DeskChannels($organizationId: OrganizationId!) { channels(input: { organizationId: $organizationId }) { id name displayName service isQueuePaused } }`;
const POST_STATUS=`query DeskPostStatus($id: PostId!) { post(input: { id: $id }) { id status dueAt channelId } }`;
const DELETE_POST=`mutation DeskDeletePost($id: PostId!) { deletePost(input: { id: $id }) { ... on DeletePostSuccess { id } ... on VoidMutationError { message } } }`;
export const CREATE_POST=`mutation DeskCreatePost($input: CreatePostInput!) { createPost(input: $input) { ... on PostActionSuccess { post { id text dueAt channelId status } } ... on MutationError { message } } }`;
export class BufferAdapter{
 constructor(env,{fetchImpl=fetch,dryRun=false}={}){this.env=env;this.fetchImpl=fetchImpl;this.dryRun=dryRun;}
 configured(){return Boolean(this.env.BUFFER_API_KEY&&this.env.BUFFER_ORGANIZATION_ID)}
 async call(query,variables={}){if(!this.configured())throw new OperationalError("BUFFER_NOT_CONFIGURED","Buffer is not configured.",{status:503,recovery:"Connect Buffer in Settings."});for(let attempt=0;attempt<3;attempt++){const {body}=await requestJson("https://api.buffer.com",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${this.env.BUFFER_API_KEY}`},body:JSON.stringify({query,variables})},{fetchImpl:this.fetchImpl});if(!body.errors?.length)return body.data;const throttled=body.errors.some(error=>error.extensions?.code==="RATE_LIMITED"||error.extensions?.code==="THROTTLED");if(throttled&&attempt<2){await new Promise(resolve=>setTimeout(resolve,250*(attempt+1)));continue}throw new OperationalError(throttled?"RATE_LIMITED":"BUFFER_GRAPHQL_ERROR",body.errors[0].message,{status:502,retryable:throttled,recovery:throttled?"Retry this destination shortly.":"Review the Buffer connection and retry."});}}
 async health(){const data=await this.call(ORGS);const match=data.account?.organizations?.some(o=>o.id===this.env.BUFFER_ORGANIZATION_ID);if(!match)throw new OperationalError("BUFFER_ORGANISATION_MISSING","The configured Buffer organisation is unavailable.",{status:503,recovery:"Update the Buffer organisation in Settings."});const channelData=await this.call(CHANNELS,{organizationId:this.env.BUFFER_ORGANIZATION_ID});return {status:"connected",channels:channelData.channels.map(c=>({service:c.service,connected:!c.isQueuePaused,name:c.displayName||c.name,id:c.id}))};}
 channelId(destination){return destination==="instagram"?this.env.BUFFER_INSTAGRAM_CHANNEL_ID:this.env.BUFFER_FACEBOOK_CHANNEL_ID}
 async status(postId){const data=await this.call(POST_STATUS,{id:postId});return {externalId:data.post.id,status:data.post.status==="sent"?"published":data.post.status==="error"?"failed":data.post.status,dueAt:data.post.dueAt};}
 async cancel(postId){const data=await this.call(DELETE_POST,{id:postId});if(!data.deletePost?.id)throw new OperationalError("BUFFER_CANCEL_FAILED",data.deletePost?.message||"Buffer could not cancel the post.",{status:422,recovery:"Open Buffer and review the scheduled post."});return {status:"cancelled",externalId:data.deletePost.id};}
 async publish({destination,document,assets,scheduledTime}){if(!assets.length)throw new OperationalError("MEDIA_REQUIRED","Artwork is required for social publishing.",{status:422,recovery:"Upload artwork and select a primary image."});if(assets.length>10)throw new OperationalError("MEDIA_LIMIT","Buffer supports up to 10 images for this destination.",{status:422,recovery:"Reduce the artwork selection to 10 images."});if(assets.some(a=>!a.url||!a.altText||!a.width||!a.height||!/^image\/(png|jpeg|webp)$/.test(a.mimeType||"")))throw new OperationalError("INVALID_MEDIA","One or more images are not ready for social publishing.",{status:422,recovery:"Check image metadata and alt text."});const channelId=this.channelId(destination);if(!channelId)throw new OperationalError("CHANNEL_DISCONNECTED",`${destination} is not connected in Buffer.`,{status:422,recovery:`Connect the ${destination} channel in Buffer, then retry this destination.`});const dueAt=scheduledTime||null;const input={text:document.summary,channelId,schedulingType:"automatic",mode:dueAt?"customScheduled":"addToQueue",...(dueAt?{dueAt}:{}),assets:assets.map(a=>({image:{url:new URL(a.url,"https://social.standardmaintenance.co.uk").href,metadata:{altText:a.altText,dimensions:{width:a.width,height:a.height}}}}))};if(this.dryRun)return {status:dueAt?"scheduled":"pending",externalId:`dry-run-${destination}`,externalUrl:null,dryRun:true};const data=await this.call(CREATE_POST,{input});if(!data.createPost?.post)throw new OperationalError("BUFFER_VALIDATION",data.createPost?.message||"Buffer did not accept the post.",{status:422,recovery:"Check the caption, media, channel, and schedule."});const post=data.createPost.post;return {status:post.status==="sent"?"published":post.status||"scheduled",externalId:post.id,externalUrl:null};}
}
export class MockBufferAdapter{constructor(results={}){this.results=results;this.calls=[]}async health(){return {status:"connected",channels:[{service:"instagram",connected:true},{service:"facebook",connected:true}]}}async status(id){return {status:"scheduled",externalId:id}}async cancel(id){return {status:"cancelled",externalId:id}}async publish(payload){this.calls.push(payload);const result=this.results[payload.destination];if(result instanceof Error)throw result;return result||{status:payload.scheduledTime?"scheduled":"pending",externalId:`buffer-${payload.destination}`}}}


