import { OperationalError } from "../core/errors.js";
import { requestJson } from "./http.js";
const SHOP_QUERY=`query DeskShopIdentity { shop { id name primaryDomain { url } } }`;
const ARTICLE_QUERY=`query DeskArticles($blogId: ID!) { blog(id: $blogId) { id handle articles(first: 100, reverse: true) { nodes { id handle } } } }`;
export const ARTICLE_CREATE=`mutation DeskArticleCreate($article: ArticleCreateInput!) { articleCreate(article: $article) { article { id title handle image { altText url } } userErrors { code field message } } }`;
export const ARTICLE_UPDATE=`mutation DeskArticleUpdate($id: ID!, $article: ArticleUpdateInput!) { articleUpdate(id: $id, article: $article) { article { id title handle image { altText url } } userErrors { code field message } } }`;
const escape=(s)=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const slug=(s)=>String(s).toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,80);
export class ShopifyAdapter{
 constructor(env,{fetchImpl=fetch,dryRun=false}={}){this.env=env;this.fetchImpl=fetchImpl;this.dryRun=dryRun;}
 configured(){return Boolean(this.env.SHOPIFY_STORE_DOMAIN&&this.env.SHOPIFY_ADMIN_ACCESS_TOKEN&&this.env.SHOPIFY_BLOG_ID)}
 async call(query,variables={}){if(!this.configured())throw new OperationalError("SHOPIFY_NOT_CONFIGURED","Shopify is not configured.",{status:503,recovery:"Connect Shopify in Settings."});const version=this.env.SHOPIFY_API_VERSION||"2026-07";for(let attempt=0;attempt<3;attempt++){const {body}=await requestJson(`https://${this.env.SHOPIFY_STORE_DOMAIN}/admin/api/${version}/graphql.json`,{method:"POST",headers:{"Content-Type":"application/json","X-Shopify-Access-Token":this.env.SHOPIFY_ADMIN_ACCESS_TOKEN},body:JSON.stringify({query,variables})},{fetchImpl:this.fetchImpl});if(!body.errors?.length)return body.data;const throttled=body.errors.some(error=>error.extensions?.code==="THROTTLED");if(throttled&&attempt<2){await new Promise(resolve=>setTimeout(resolve,250*(attempt+1)));continue}throw new OperationalError(throttled?"RATE_LIMITED":"SHOPIFY_GRAPHQL_ERROR",body.errors[0].message,{status:502,retryable:throttled,recovery:throttled?"Retry this destination shortly.":"Review Shopify permissions and retry."});}}
 async health(){const data=await this.call(SHOP_QUERY);return {status:"connected",shop:data.shop.name};}
 input(document,assets,publish){const handle=`smcu-${slug(document.id)}-${slug(document.title)}`;return {blogId:this.env.SHOPIFY_BLOG_ID,title:document.title,handle,author:{name:document.author},body:`<p>${escape(document.summary)}</p>`,summary:document.summary,tags:document.tags,isPublished:Boolean(publish),image:assets[0]?{url:new URL(assets[0].url,"https://social.standardmaintenance.co.uk").href,altText:assets[0].altText}:undefined};}
 async publish({document,assets,publish=true}){const article=this.input(document,assets,publish);if(this.dryRun)return {status:publish?"published":"draft",externalId:"dry-run-shopify",externalUrl:null,dryRun:true};const existing=await this.call(ARTICLE_QUERY,{blogId:this.env.SHOPIFY_BLOG_ID});const node=existing.blog?.articles?.nodes?.find(item=>item.handle===article.handle);const data=node?await this.call(ARTICLE_UPDATE,{id:node.id,article}):await this.call(ARTICLE_CREATE,{article});const payload=node?data.articleUpdate:data.articleCreate;if(payload.userErrors?.length)throw new OperationalError("SHOPIFY_VALIDATION",payload.userErrors[0].message,{status:422,recovery:"Correct the communication content or Shopify configuration."});return {status:publish?"published":"draft",externalId:payload.article.id,externalUrl:this.env.SHOPIFY_PUBLIC_BLOG_HANDLE?`https://${this.env.SHOPIFY_PUBLIC_DOMAIN||this.env.SHOPIFY_STORE_DOMAIN}/blogs/${this.env.SHOPIFY_PUBLIC_BLOG_HANDLE}/${article.handle}`:null};}
}
export class MockShopifyAdapter{constructor(result={status:"published",externalId:"gid://shopify/Article/1",externalUrl:"https://example.test/blogs/news/smcu"}){this.result=result;this.calls=[]}async health(){return {status:"connected",shop:"SMCU Test"}}async publish(payload){this.calls.push(payload);if(this.result instanceof Error)throw this.result;return this.result}}


