import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import { MemoryAuthoringStore, mergeAuthoringRepository, resolvedCopy } from "../worker/storage/authoring.js";
import { AuthoringService, communicationBlockers } from "../worker/authoring/service.js";
import { sanitizeHtml } from "../worker/authoring/content.js";

const clock=()=>new Date("2026-07-26T10:00:00.000Z");
const campaign={name:"Launch",purpose:"Promote",description:"Autumn launch",status:"Active",startDate:"2026-07-26",targetDate:"2026-08-10",channels:["Shopify","Instagram"],tasks:[{id:"write",label:"Write copy",completed:false}],notes:"Private"};
const communication={title:"Launch memo",workingTitle:"Autumn",type:"Company Memo",campaignId:"CMP-001",status:"Draft",channels:["Shopify","Instagram","Facebook"],publicationDate:null,mainContentHtml:"<h2>Launch</h2><p>Clean copy.</p>",summary:"Summary",callToAction:"Shop",shopifyTitle:"Launch",shopifyContentHtml:"",instagramCaption:"",facebookCaption:"",promotionalCopy:"Short",useMainShopify:true,useMainInstagram:true,useMainFacebook:true,internalNotes:"Draft"};
const assets={records:new Map(),async list(id){return structuredClone(this.records.get(id)||[])}};

test("campaign create, edit, duplicate, archive, tasks and server IDs",async()=>{const store=new MemoryAuthoringStore({clock});const created=await store.createCampaign(campaign);assert.equal(created.id,"CMP-002");assert.equal(created.tasks[0].label,"Write copy");const edited=await store.updateCampaign(created.id,{...campaign,version:created.version,name:"Autumn launch",tasks:[{id:"write",label:"Write copy",completed:true},{label:"Review",completed:false}]});assert.equal(edited.version,2);assert.equal(edited.tasks.length,2);const duplicate=await store.duplicateCampaign(created.id);assert.equal(duplicate.id,"CMP-003");assert.equal(duplicate.status,"Draft");assert.ok(duplicate.tasks.every(x=>!x.completed));const archived=await store.updateCampaign(created.id,{...edited,version:edited.version,status:"Archived"});assert.equal(archived.status,"Archived")});

test("communication create, draft edit, duplicate, archive and relationship persistence",async()=>{const store=new MemoryAuthoringStore({clock});const c=await store.createCampaign(campaign);const created=await store.createCommunication({...communication,campaignId:c.id});assert.equal(created.id,"CN-002");let snap=await store.snapshot();assert.deepEqual(snap.campaigns[0].communications,[created.id]);const edited=await store.updateCommunication(created.id,{...created,version:created.version,title:"Revised memo",status:"In progress"});assert.equal(edited.title,"Revised memo");const duplicate=await store.duplicateCommunication(created.id);assert.equal(duplicate.status,"Draft");assert.equal(duplicate.campaignId,c.id);const archived=await store.updateCommunication(created.id,{...edited,version:edited.version,status:"Archived"});assert.equal(archived.status,"Archived")});

test("stale updates are rejected and HTML is sanitised",async()=>{const store=new MemoryAuthoringStore({clock});const c=await store.createCampaign(campaign);await assert.rejects(()=>store.updateCampaign(c.id,{...c,version:0}),e=>e.code==="STALE_UPDATE");const cleaned=sanitizeHtml('<script>alert(1)</script><h2 onclick="x">Safe</h2><a href="javascript:bad">link</a><a href="https://smcu.example">ok</a>');assert.doesNotMatch(cleaned,/script|onclick|javascript/i);assert.match(cleaned,/https:\/\/smcu\.example/)});

test("destination copy inherits main content until customised",()=>{const inherited=resolvedCopy(communication);assert.equal(inherited.instagram,"Launch\nClean copy.");assert.match(inherited.shopifyHtml,/Clean copy/);const custom=resolvedCopy({...communication,useMainInstagram:false,instagramCaption:"Destination copy"});assert.equal(custom.instagram,"Destination copy")});

test("readiness blockers are exact and mark ready preserves artwork",async()=>{const store=new MemoryAuthoringStore({clock});const c=await store.createCampaign(campaign);const record=await store.createCommunication({...communication,campaignId:c.id});assert.deepEqual(communicationBlockers(record,[],clock),["Missing artwork."]);assets.records.set(record.id,[{id:"AST-ABC",url:"https://example.test/assets/a.png",altText:"Model wearing SMCU shirt",primary:true,order:0}]);const service=new AuthoringService({store,assets,clock});const ready=await service.markReady(record.id,record.version);assert.equal(ready.status,"Ready");assert.equal((await assets.list(record.id))[0].id,"AST-ABC")});

test("preview uses saved variants, ordered artwork and public URLs",async()=>{const store=new MemoryAuthoringStore({clock});const c=await store.createCampaign(campaign);const record=await store.createCommunication({...communication,campaignId:c.id});assets.records.set(record.id,[{id:"B",url:"https://example.test/b.png",altText:"Second",primary:false,order:1},{id:"A",url:"https://example.test/a.png",altText:"First",primary:true,order:0}]);const preview=await new AuthoringService({store,assets,clock}).preview(record.id);assert.equal(preview.communication.title,"Launch memo");assert.equal(preview.assets[1].url,"https://example.test/a.png");assert.equal(preview.readiness.ready,true)});

test("CMP-001 and CN-001 migration keeps canonical IDs and artwork contracts",async()=>{const seed=JSON.parse(await fs.readFile(new URL("../communications/data/repository.json",import.meta.url),"utf8"));const snapshot={campaigns:[{id:"CMP-001",name:"Seed",status:"Complete",tasks:[],channels:[],communications:["CN-001"],createdAt:"2026-01-01T00:00:00Z",updatedAt:"2026-01-01T00:00:00Z"}],communications:[{id:"CN-001",title:"Seed communication",type:"Company Memo",campaignId:"CMP-001",status:"Published",channels:[],mainContentHtml:"<p>Seed</p>",createdAt:"2026-01-01T00:00:00Z",updatedAt:"2026-01-01T00:00:00Z",internalNotes:""}]};const merged=mergeAuthoringRepository(seed,snapshot);assert.equal(merged.campaigns[0].id,"CMP-001");assert.equal(merged.documents[0].id,"CN-001");assert.deepEqual(merged.documents[0].assets,seed.documents.find(x=>x.id==="CN-001").assets);const urls=seed.assets.filter(x=>(x.communicationId||x.communication)==="CN-001").map(x=>x.url);assert.ok(urls.length>=3);assert.ok(urls.every(x=>x.toLowerCase().includes("cn-001")))});

test("authoring UI warns about unsaved changes and pastes plain text",async()=>{const source=await fs.readFile(new URL("../communications/modules/app.js",import.meta.url),"utf8");assert.match(source,/beforeunload/);assert.match(source,/clipboardData\.getData\("text\/plain"\)/);assert.match(source,/data-character-count/)});