import { OperationalError } from "../core/errors.js";
import { sanitizeHtml, plainText } from "../authoring/content.js";

export const CAMPAIGN_STATUSES=["Draft","Active","Paused","Complete","Archived"];
export const COMMUNICATION_STATUSES=["Draft","In progress","Ready","Scheduled","Published","Archived"];
export const COMMUNICATION_TYPES=["Company Memo","Product announcement","Social post","Campaign notice","General update"];
export const CHANNELS=["Shopify","Instagram","Facebook"];
const parse=(value,fallback=[])=>{try{return JSON.parse(value)}catch{return fallback}};
const required=(value,label,max=200)=>{const text=String(value||"").trim();if(!text)throw new OperationalError("VALIDATION_ERROR",`${label} is required.`,{status:422});if(text.length>max)throw new OperationalError("VALIDATION_ERROR",`${label} is too long.`,{status:422});return text};
const optional=(value,max=5000)=>{const text=String(value||"").trim();if(text.length>max)throw new OperationalError("VALIDATION_ERROR","A field is too long.",{status:422});return text};
const date=value=>{const text=String(value||"").trim();if(text&&!/^\d{4}-\d{2}-\d{2}(?:T\d{2}:\d{2}(?::\d{2}(?:\.\d{3})?)?Z?)?$/.test(text))throw new OperationalError("VALIDATION_ERROR","A date is invalid.",{status:422});return text||null};
const list=(value,allowed,label)=>{if(!Array.isArray(value)||value.some(item=>!allowed.includes(item))||new Set(value).size!==value.length)throw new OperationalError("VALIDATION_ERROR",`${label} are invalid.`,{status:422});return value};
const tasks=value=>{if(!Array.isArray(value)||value.length>40)throw new OperationalError("VALIDATION_ERROR","Campaign tasks are invalid.",{status:422});return value.map((item,index)=>({id:String(item.id||`task-${index+1}`).replace(/[^a-z0-9-]/gi,"-").slice(0,60),label:required(item.label,"Task",160),completed:Boolean(item.completed)}))};
const mapCampaign=row=>row?{id:row.campaign_id,name:row.name,title:row.name,purpose:row.purpose,description:row.description,status:row.status,startDate:row.start_date,targetDate:row.target_date,targetPublishDate:row.target_date,channels:parse(row.channels_json),tasks:parse(row.tasks_json),checklist:parse(row.tasks_json),notes:row.notes,createdAt:row.created_at,updatedAt:row.updated_at,created:row.created_at.slice(0,10),modified:row.updated_at.slice(0,10),version:row.version,communications:[]}:null;
const mapCommunication=row=>row?{id:row.communication_id,title:row.title,workingTitle:row.working_title,type:row.communication_type,documentType:row.communication_type,campaignId:row.campaign_id,status:row.status,channels:parse(row.channels_json),publicationDate:row.publication_date,publishDate:row.publication_date?.slice(0,10)||null,mainContentHtml:row.main_content_html,summary:row.summary,callToAction:row.call_to_action,shopifyTitle:row.shopify_title,shopifyContentHtml:row.shopify_content_html,instagramCaption:row.instagram_caption,facebookCaption:row.facebook_caption,promotionalCopy:row.promotional_copy,useMainShopify:Boolean(row.use_main_shopify),useMainInstagram:Boolean(row.use_main_instagram),useMainFacebook:Boolean(row.use_main_facebook),internalNotes:row.internal_notes,createdAt:row.created_at,updatedAt:row.updated_at,createdDate:row.created_at.slice(0,10),modifiedDate:row.updated_at,version:row.version}:null;
function campaignInput(body,current={}){return {name:required(body.name??current.name,"Campaign name"),purpose:optional(body.purpose??current.purpose,1000),description:optional(body.description??current.description,5000),status:CAMPAIGN_STATUSES.includes(body.status??current.status)?body.status??current.status:"Draft",startDate:date(body.startDate??current.startDate),targetDate:date(body.targetDate??current.targetDate),channels:list(body.channels??current.channels??[],CHANNELS,"Campaign channels"),tasks:tasks(body.tasks??current.tasks??[]),notes:optional(body.notes??current.notes,10000)}}
function communicationInput(body,current={}){const type=body.type??current.type??"General update",status=body.status??current.status??"Draft";if(!COMMUNICATION_TYPES.includes(type)||!COMMUNICATION_STATUSES.includes(status))throw new OperationalError("VALIDATION_ERROR","Communication type or status is invalid.",{status:422});return {title:required(body.title??current.title,"Communication title"),workingTitle:optional(body.workingTitle??current.workingTitle,200),type,campaignId:body.campaignId===null||body.campaignId===""?null:String((body.campaignId??current.campaignId)||"")||null,status,channels:list(body.channels??current.channels??[],CHANNELS,"Communication channels"),publicationDate:date(body.publicationDate??current.publicationDate),mainContentHtml:sanitizeHtml(body.mainContentHtml??current.mainContentHtml),summary:optional(body.summary??current.summary,1000),callToAction:optional(body.callToAction??current.callToAction,500),shopifyTitle:optional(body.shopifyTitle??current.shopifyTitle,200),shopifyContentHtml:sanitizeHtml(body.shopifyContentHtml??current.shopifyContentHtml),instagramCaption:optional(body.instagramCaption??current.instagramCaption,2200),facebookCaption:optional(body.facebookCaption??current.facebookCaption,5000),promotionalCopy:optional(body.promotionalCopy??current.promotionalCopy,500),useMainShopify:Boolean(body.useMainShopify??current.useMainShopify??true),useMainInstagram:Boolean(body.useMainInstagram??current.useMainInstagram??true),useMainFacebook:Boolean(body.useMainFacebook??current.useMainFacebook??true),internalNotes:optional(body.internalNotes??current.internalNotes,10000)}}
export function resolvedCopy(record){const main=plainText(record.mainContentHtml);return {shopifyHtml:record.useMainShopify?record.mainContentHtml:record.shopifyContentHtml,instagram:record.useMainInstagram?main:record.instagramCaption,facebook:record.useMainFacebook?main:record.facebookCaption,promotional:record.promotionalCopy||main}}
export function mergeAuthoringRepository(seed,snapshot){const copy=structuredClone(seed);copy.campaigns=snapshot.campaigns.map(c=>({...c,owner:"Jamie",priority:"Normal",assets:[],calendar:[],shopify:{},buffer:{},instagram:{},facebook:{},analytics:{},progress:{source:"checklist"},history:[]}));copy.documents=snapshot.communications.map(c=>{const seeded=seed.documents.find(document=>document.id===c.id);return {...c,department:"Communications",section:seeded?.section||"company-notices",author:"Jamie",tags:seeded?.tags||[],assets:seeded?.assets||[],shopify:{},buffer:{},analytics:{},history:[],checklist:[],notes:c.internalNotes?[c.internalNotes]:[],workflow:{needsArtwork:false,needsShopify:c.channels.includes("Shopify"),needsScheduling:c.channels.some(x=>x!=="Shopify"),needsReview:["Draft","In progress"].includes(c.status),readyToPublish:c.status==="Ready",awaitingAssets:false}}});return copy}
export class D1AuthoringStore{
 constructor(db,clock=()=>new Date()){if(!db)throw new OperationalError("STORAGE_NOT_CONFIGURED","Authoring storage is not configured.",{status:503});this.db=db;this.clock=clock}
 async snapshot(){const [campaigns,communications]=await Promise.all([this.listCampaigns(),this.listCommunications()]);const byId=new Map(campaigns.map(c=>[c.id,c]));communications.forEach(c=>{if(c.campaignId&&byId.has(c.campaignId))byId.get(c.campaignId).communications.push(c.id)});return {campaigns,communications}}
 async listCampaigns(){const r=await this.db.prepare("SELECT * FROM operational_campaigns ORDER BY CASE status WHEN 'Active' THEN 0 WHEN 'Draft' THEN 1 ELSE 2 END,target_date,created_at").all();return (r.results||[]).map(mapCampaign)}
 async listCommunications(){const r=await this.db.prepare("SELECT * FROM operational_communications ORDER BY updated_at DESC").all();return (r.results||[]).map(mapCommunication)}
 async getCampaign(id){return mapCampaign(await this.db.prepare("SELECT * FROM operational_campaigns WHERE campaign_id=?").bind(id).first())}
 async getCommunication(id){return mapCommunication(await this.db.prepare("SELECT * FROM operational_communications WHERE communication_id=?").bind(id).first())}
 async next(entity,prefix){const row=await this.db.prepare("UPDATE authoring_sequences SET next_number=next_number+1 WHERE entity=? RETURNING next_number-1 AS number").bind(entity).first();if(!row)throw new OperationalError("STORAGE_ERROR","ID generation failed.",{status:503});return `${prefix}-${String(row.number).padStart(3,"0")}`}
 async createCampaign(body){const value=campaignInput(body),id=await this.next("campaign","CMP"),now=this.clock().toISOString();await this.db.prepare("INSERT INTO operational_campaigns VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(id,value.name,value.purpose,value.description,value.status,value.startDate,value.targetDate,JSON.stringify(value.channels),JSON.stringify(value.tasks),value.notes,now,now,1).run();return this.getCampaign(id)}
 async updateCampaign(id,body){const current=await this.getCampaign(id);if(!current)throw new OperationalError("CAMPAIGN_NOT_FOUND","Campaign was not found.",{status:404});if(Number(body.version)!==current.version)throw new OperationalError("STALE_UPDATE","Campaign changed after you opened it.",{status:409,recovery:"Refresh and review the latest version."});const value=campaignInput(body,current),now=this.clock().toISOString();const r=await this.db.prepare("UPDATE operational_campaigns SET name=?,purpose=?,description=?,status=?,start_date=?,target_date=?,channels_json=?,tasks_json=?,notes=?,updated_at=?,version=version+1 WHERE campaign_id=? AND version=?").bind(value.name,value.purpose,value.description,value.status,value.startDate,value.targetDate,JSON.stringify(value.channels),JSON.stringify(value.tasks),value.notes,now,id,current.version).run();if(!r.meta?.changes)throw new OperationalError("STALE_UPDATE","Campaign changed while saving.",{status:409});return this.getCampaign(id)}
 async duplicateCampaign(id){const current=await this.getCampaign(id);if(!current)throw new OperationalError("CAMPAIGN_NOT_FOUND","Campaign was not found.",{status:404});return this.createCampaign({...current,name:`${current.name} copy`,status:"Draft",tasks:current.tasks.map(x=>({...x,completed:false}))})}
 async deleteCampaign(id){const linked=await this.db.prepare("SELECT COUNT(*) count FROM operational_communications WHERE campaign_id=?").bind(id).first();if(linked?.count)throw new OperationalError("CAMPAIGN_IN_USE","Move or archive linked communications first.",{status:409});await this.db.prepare("DELETE FROM operational_campaigns WHERE campaign_id=? AND status='Draft'").bind(id).run();return {deleted:true,id}}
 async createCommunication(body){const value=communicationInput(body),id=await this.next("communication","CN"),now=this.clock().toISOString();if(value.campaignId&&!await this.getCampaign(value.campaignId))throw new OperationalError("CAMPAIGN_NOT_FOUND","Choose an existing campaign.",{status:422});await this.db.prepare("INSERT INTO operational_communications VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(id,value.title,value.workingTitle,value.type,value.campaignId,value.status,JSON.stringify(value.channels),value.publicationDate,value.mainContentHtml,value.summary,value.callToAction,value.shopifyTitle,value.shopifyContentHtml,value.instagramCaption,value.facebookCaption,value.promotionalCopy,value.useMainShopify?1:0,value.useMainInstagram?1:0,value.useMainFacebook?1:0,value.internalNotes,now,now,1).run();return this.getCommunication(id)}
 async updateCommunication(id,body,{allowReady=false}={}){const current=await this.getCommunication(id);if(!current)throw new OperationalError("COMMUNICATION_NOT_FOUND","Communication was not found.",{status:404});if(Number(body.version)!==current.version)throw new OperationalError("STALE_UPDATE","Communication changed after you opened it.",{status:409,recovery:"Refresh and review the latest version."});const value=communicationInput(body,current);if(value.status==="Ready"&&current.status!=="Ready"&&!allowReady)throw new OperationalError("READINESS_REQUIRED","Use Mark ready so requirements can be checked.",{status:409});if(value.campaignId&&!await this.getCampaign(value.campaignId))throw new OperationalError("CAMPAIGN_NOT_FOUND","Choose an existing campaign.",{status:422});const now=this.clock().toISOString();const r=await this.db.prepare("UPDATE operational_communications SET title=?,working_title=?,communication_type=?,campaign_id=?,status=?,channels_json=?,publication_date=?,main_content_html=?,summary=?,call_to_action=?,shopify_title=?,shopify_content_html=?,instagram_caption=?,facebook_caption=?,promotional_copy=?,use_main_shopify=?,use_main_instagram=?,use_main_facebook=?,internal_notes=?,updated_at=?,version=version+1 WHERE communication_id=? AND version=?").bind(value.title,value.workingTitle,value.type,value.campaignId,value.status,JSON.stringify(value.channels),value.publicationDate,value.mainContentHtml,value.summary,value.callToAction,value.shopifyTitle,value.shopifyContentHtml,value.instagramCaption,value.facebookCaption,value.promotionalCopy,value.useMainShopify?1:0,value.useMainInstagram?1:0,value.useMainFacebook?1:0,value.internalNotes,now,id,current.version).run();if(!r.meta?.changes)throw new OperationalError("STALE_UPDATE","Communication changed while saving.",{status:409});return this.getCommunication(id)}
 async duplicateCommunication(id){const current=await this.getCommunication(id);if(!current)throw new OperationalError("COMMUNICATION_NOT_FOUND","Communication was not found.",{status:404});return this.createCommunication({...current,title:`${current.title} copy`,status:"Draft",publicationDate:null})}
 async deleteCommunication(id){const assets=await this.db.prepare("SELECT COUNT(*) count FROM communication_assets WHERE communication_id=? AND storage_kind='r2'").bind(id).first();if(assets?.count)throw new OperationalError("COMMUNICATION_IN_USE","Delete uploaded artwork before deleting this draft.",{status:409});await this.db.prepare("DELETE FROM operational_communications WHERE communication_id=? AND status='Draft'").bind(id).run();return {deleted:true,id}}
}

export class MemoryAuthoringStore{
 constructor({campaigns=[],communications=[],clock=()=>new Date()}={}){this.campaigns=structuredClone(campaigns);this.communications=structuredClone(communications);this.clock=clock;this.nextCampaign=Math.max(1,...this.campaigns.map(x=>Number(x.id?.split("-")[1])||0))+1;this.nextCommunication=Math.max(1,...this.communications.map(x=>Number(x.id?.split("-")[1])||0))+1}
 stamp(record,id){const now=this.clock().toISOString();return {...record,id,createdAt:now,updatedAt:now,created:now.slice(0,10),modified:now.slice(0,10),createdDate:now.slice(0,10),modifiedDate:now,version:1}}
 async snapshot(){const campaigns=structuredClone(this.campaigns).map(c=>({...c,communications:this.communications.filter(x=>x.campaignId===c.id).map(x=>x.id)}));return {campaigns,communications:structuredClone(this.communications)}}
 async getCampaign(id){return structuredClone(this.campaigns.find(x=>x.id===id)||null)}
 async getCommunication(id){return structuredClone(this.communications.find(x=>x.id===id)||null)}
 async createCampaign(body){const value=campaignInput(body),id=`CMP-${String(this.nextCampaign++).padStart(3,"0")}`,record=this.stamp({...value,title:value.name,checklist:value.tasks},id);this.campaigns.push(record);return structuredClone(record)}
 async updateCampaign(id,body){const index=this.campaigns.findIndex(x=>x.id===id),current=this.campaigns[index];if(!current)throw new OperationalError("CAMPAIGN_NOT_FOUND","Campaign was not found.",{status:404});if(Number(body.version)!==current.version)throw new OperationalError("STALE_UPDATE","Campaign changed after you opened it.",{status:409});const value=campaignInput(body,current),updated={...current,...value,title:value.name,checklist:value.tasks,updatedAt:this.clock().toISOString(),version:current.version+1};this.campaigns[index]=updated;return structuredClone(updated)}
 async duplicateCampaign(id){const current=await this.getCampaign(id);if(!current)throw new OperationalError("CAMPAIGN_NOT_FOUND","Campaign was not found.",{status:404});return this.createCampaign({...current,name:`${current.name} copy`,status:"Draft",tasks:current.tasks.map(x=>({...x,completed:false}))})}
 async deleteCampaign(id){if(this.communications.some(x=>x.campaignId===id))throw new OperationalError("CAMPAIGN_IN_USE","Move or archive linked communications first.",{status:409});this.campaigns=this.campaigns.filter(x=>!(x.id===id&&x.status==="Draft"));return {deleted:true,id}}
 async createCommunication(body){const value=communicationInput(body);if(value.campaignId&&!this.campaigns.some(x=>x.id===value.campaignId))throw new OperationalError("CAMPAIGN_NOT_FOUND","Choose an existing campaign.",{status:422});const id=`CN-${String(this.nextCommunication++).padStart(3,"0")}`,record=this.stamp(value,id);this.communications.push(record);return structuredClone(record)}
 async updateCommunication(id,body,{allowReady=false}={}){const index=this.communications.findIndex(x=>x.id===id),current=this.communications[index];if(!current)throw new OperationalError("COMMUNICATION_NOT_FOUND","Communication was not found.",{status:404});if(Number(body.version)!==current.version)throw new OperationalError("STALE_UPDATE","Communication changed after you opened it.",{status:409});const value=communicationInput(body,current);if(value.status==="Ready"&&current.status!=="Ready"&&!allowReady)throw new OperationalError("READINESS_REQUIRED","Use Mark ready so requirements can be checked.",{status:409});if(value.campaignId&&!this.campaigns.some(x=>x.id===value.campaignId))throw new OperationalError("CAMPAIGN_NOT_FOUND","Choose an existing campaign.",{status:422});const updated={...current,...value,updatedAt:this.clock().toISOString(),modifiedDate:this.clock().toISOString(),version:current.version+1};this.communications[index]=updated;return structuredClone(updated)}
 async duplicateCommunication(id){const current=await this.getCommunication(id);if(!current)throw new OperationalError("COMMUNICATION_NOT_FOUND","Communication was not found.",{status:404});return this.createCommunication({...current,title:`${current.title} copy`,status:"Draft",publicationDate:null})}
 async deleteCommunication(id){this.communications=this.communications.filter(x=>!(x.id===id&&x.status==="Draft"));return {deleted:true,id}}
}