import { OperationalError } from "../core/errors.js";
const FIELDS="communication_id,campaign_id,destination,requested_action,idempotency_key,status,scheduled_time,external_platform_id,external_url,attempt_count,created_at,updated_at,completed_at,failure_code,recovery_message,request_fingerprint,correlation_id";
export class D1PublicationStore {
 constructor(db,clock=()=>new Date()){if(!db)throw new OperationalError("STORAGE_NOT_CONFIGURED","Publication storage is not configured.",{status:503,recovery:"Configure the PUBLICATIONS_DB binding in Cloudflare."});this.db=db;this.clock=clock;}
 async find(key,destination){return this.db.prepare(`SELECT ${FIELDS} FROM publication_results WHERE idempotency_key=? AND destination=?`).bind(key,destination).first();}
 async list(communicationId){const result=await this.db.prepare(`SELECT ${FIELDS} FROM publication_results WHERE communication_id=? ORDER BY created_at DESC`).bind(communicationId).all();return result.results||[];}
 async reserve(record){const now=this.clock().toISOString(); await this.db.prepare(`INSERT OR IGNORE INTO publication_results (${FIELDS}) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(record.communicationId,record.campaignId||null,record.destination,record.requestedAction,record.idempotencyKey,"pending",record.scheduledTime||null,null,null,0,now,now,null,null,null,record.requestFingerprint,record.correlationId).run(); return this.find(record.idempotencyKey,record.destination);}
 async complete(key,destination,result){const now=this.clock().toISOString(); await this.db.prepare(`UPDATE publication_results SET status=?,external_platform_id=?,external_url=?,attempt_count=attempt_count+1,updated_at=?,completed_at=?,failure_code=NULL,recovery_message=NULL WHERE idempotency_key=? AND destination=?`).bind(result.status,result.externalId||null,result.externalUrl||null,now,["published","scheduled"].includes(result.status)?now:null,key,destination).run();return this.find(key,destination);}
 async fail(key,destination,error){const now=this.clock().toISOString();await this.db.prepare(`UPDATE publication_results SET status='failed',attempt_count=attempt_count+1,updated_at=?,failure_code=?,recovery_message=? WHERE idempotency_key=? AND destination=?`).bind(now,error.code,error.recovery,key,destination).run();return this.find(key,destination);}
}
export class MemoryPublicationStore {
 constructor(clock=()=>new Date()){this.rows=[];this.clock=clock;}
 async find(k,d){return this.rows.find(x=>x.idempotency_key===k&&x.destination===d)||null} async list(id){return this.rows.filter(x=>x.communication_id===id)}
 async reserve(r){let row=this.rows.find(x=>x.idempotency_key===r.idempotencyKey&&x.destination===r.destination); if(row)return row; const now=this.clock().toISOString();row={communication_id:r.communicationId,campaign_id:r.campaignId||null,destination:r.destination,requested_action:r.requestedAction,idempotency_key:r.idempotencyKey,status:"pending",scheduled_time:r.scheduledTime||null,external_platform_id:null,external_url:null,attempt_count:0,created_at:now,updated_at:now,completed_at:null,failure_code:null,recovery_message:null,request_fingerprint:r.requestFingerprint,correlation_id:r.correlationId};this.rows.push(row);return row;}
 async complete(k,d,result){const r=await this.find(k,d);Object.assign(r,{status:result.status,external_platform_id:result.externalId||null,external_url:result.externalUrl||null,attempt_count:r.attempt_count+1,updated_at:this.clock().toISOString(),completed_at:this.clock().toISOString(),failure_code:null,recovery_message:null});return r;}
 async fail(k,d,e){const r=await this.find(k,d);Object.assign(r,{status:"failed",attempt_count:r.attempt_count+1,updated_at:this.clock().toISOString(),failure_code:e.code,recovery_message:e.recovery});return r;}
}

