import {getRuntimeAuthProvider,isSafeReturnPath} from "./auth.js";
import {imageApi} from "./integrations.js";
import {renderShell,renderImages,renderSettings,renderLogin,renderUnauthorised,renderError} from "./ui.js";
const LIBRARY_ID="CN-001",body=document.body,mount=document.querySelector("#app"),base=body.dataset.base||".",page=body.dataset.page||"images",route=path=>`${base}/${path}`,auth=getRuntimeAuthProvider();let session;
start();
async function start(){try{document.title="SMCU Image Library";if(page==="login")return showLogin();if(page==="unauthorised"){mount.innerHTML=renderUnauthorised(route);return}session=await auth.getSession();if(!session){location.replace(`${route("login/index.html")}?returnTo=${encodeURIComponent(location.pathname+location.search)}`);return}if(page==="settings")await showSettings();else await showImages();bindLogout()}catch(error){console.error(error);mount.innerHTML=renderError(error.message)}}
function showLogin(){const local=auth.id==="local-development",requested=new URLSearchParams(location.search).get("returnTo")||"/communications/",returnPath=isSafeReturnPath(requested)?requested:"/communications/";mount.innerHTML=renderLogin({local,returnPath});document.querySelector("[data-local-login]")?.addEventListener("click",async()=>{await auth.signIn();location.replace(returnPath)})}
async function showImages(){const {assets}=await imageApi.list(LIBRARY_ID);mount.innerHTML=renderShell(renderImages(assets),{route,active:"images",session});bindGallery(assets);bindUpload()}
async function showSettings(){let health={storage:"unavailable",artwork:"unavailable"};try{health=await imageApi.health()}catch{}mount.innerHTML=renderShell(renderSettings(health,session,auth),{route,active:"settings",session})}
function bindLogout(){document.querySelector("[data-logout]")?.addEventListener("click",async()=>{const target=await auth.signOut();location.assign(target||route("login/index.html"))})}
function bindUpload(){const zone=document.querySelector("[data-dropzone]"),input=document.querySelector("[data-upload-input]"),progress=document.querySelector("[data-upload-progress]"),status=document.querySelector("[data-upload-status]");if(!zone)return;const choose=()=>input.click(),report=(message,state="")=>{status.textContent=message;zone.dataset.state=state};document.querySelector("[data-choose-files]").addEventListener("click",event=>{event.stopPropagation();choose()});zone.addEventListener("click",event=>{if(!event.target.closest("button"))choose()});zone.addEventListener("keydown",event=>{if(["Enter"," "].includes(event.key)){event.preventDefault();choose()}});for(const type of ["dragenter","dragover"]){zone.addEventListener(type,event=>{event.preventDefault();zone.classList.add("is-dragging")})}for(const type of ["dragleave","drop"]){zone.addEventListener(type,event=>{event.preventDefault();zone.classList.remove("is-dragging")})}zone.addEventListener("drop",event=>uploadFiles([...event.dataTransfer.files]));input.addEventListener("change",()=>uploadFiles([...input.files]));async function uploadFiles(files){if(!files.length)return;progress.hidden=false;progress.value=0;report(`Uploading ${files.length} image${files.length===1?"":"s"}…`,"uploading");let duplicates=0;try{for(let index=0;index<files.length;index++){const result=await imageApi.upload(LIBRARY_ID,files[index],percent=>progress.value=Math.round((index+percent/100)/files.length*100));if(result.duplicate)duplicates++}progress.value=100;report(duplicates?`${files.length-duplicates} uploaded; ${duplicates} already existed.`:`${files.length} image${files.length===1?"":"s"} uploaded.`,duplicates?"duplicate":"success");setTimeout(()=>location.reload(),700)}catch(error){progress.hidden=true;report(`${error.message} ${error.details?.recovery||""}`.trim(),"error")}finally{input.value=""}}}
function bindGallery(assets){const dialog=document.querySelector(".preview-dialog"),previewImage=dialog?.querySelector("img");document.querySelectorAll("[data-preview]").forEach(control=>control.addEventListener("click",()=>{previewImage.src=control.dataset.preview;previewImage.alt=control.dataset.alt||"Image preview";dialog.showModal()}));dialog?.querySelector("[data-close-preview]").addEventListener("click",()=>dialog.close());dialog?.addEventListener("click",event=>{if(event.target===dialog)dialog.close()});document.querySelectorAll(".library-url input").forEach(input=>input.value=new URL(input.value,location.origin).href);document.querySelectorAll("[data-copy-url]").forEach(button=>button.addEventListener("click",async()=>{await navigator.clipboard.writeText(new URL(button.dataset.copyUrl,location.origin).href);notify("Public URL copied") }));document.querySelectorAll(".library-image").forEach(card=>{const asset=assets.find(item=>item.id===card.dataset.assetId);card.querySelector("[data-delete]")?.addEventListener("click",async()=>{if(!confirm(`Delete ${asset.filename}? This cannot be undone.`))return;try{await imageApi.remove(asset.id);location.reload()}catch(error){if(error.details?.code==="ASSET_IN_USE"&&confirm(`${error.message} ${error.details.recovery} Delete anyway?`)){await imageApi.remove(asset.id,true);location.reload()}else notify(error.message)}});card.querySelector("[data-replace]")?.addEventListener("change",async event=>{const file=event.target.files[0];if(!file||!confirm(`Replace ${asset.filename}? Its public URL will stay the same.`))return;try{await imageApi.replace(asset.id,file,false);location.reload()}catch(error){if(error.details?.code==="ASSET_IN_USE"&&confirm(`${error.message} ${error.details.recovery} Replace anyway?`)){await imageApi.replace(asset.id,file,true);location.reload()}else notify(error.message)}})})}
function notify(message){const toast=document.querySelector(".toast");if(!toast)return;toast.textContent=message;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),1800)}
