const ESCAPE = { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" };
const NAVIGATION = [["dashboard", "Dashboard", "index.html"], ["communications", "Communications", "communications/index.html"], ["campaigns", "Campaigns", "campaigns/index.html"], ["publishing", "Publishing", "publishing/index.html"], ["settings", "Settings", "settings/index.html"]];
export const escapeHtml = (value = "") => String(value).replace(/[&<>"']/g, (character) => ESCAPE[character]);
export const formatDate = (value) => value ? new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(`${value}T12:00:00`)) : "Not set";
export const statusChip = (status) => `<span class="status status-${String(status).toLowerCase().replace(/\s+/g, "-")}">${escapeHtml(status)}</span>`;

export function renderShell(content, { route, active = "dashboard", session, breadcrumbs = [] }) {
  const nav = NAVIGATION.map(([key, label, path], index) => `<a href="${route(path)}" class="nav-link${active === key ? " is-active" : ""}"${active === key ? ' aria-current="page"' : ""}><span>${String(index + 1).padStart(2, "0")}</span>${label}</a>`).join("");
  const crumbs = breadcrumbs.length ? `<nav class="breadcrumbs" aria-label="Breadcrumb"><a href="${route("index.html")}">Desk</a>${breadcrumbs.map((item, index) => `<span>/</span>${item.href && index < breadcrumbs.length - 1 ? `<a href="${item.href}">${escapeHtml(item.label)}</a>` : `<b aria-current="page">${escapeHtml(item.label)}</b>`}`).join("")}</nav>` : "";
  return `<div class="app-shell"><aside class="sidebar"><a class="brand" href="${route("index.html")}"><small>Standard Maintenance<br>Company Uniform</small><strong>Communications<br>Desk</strong></a><nav aria-label="Primary navigation">${nav}</nav><div class="operator"><span>Operator</span><strong>${escapeHtml(session.operator.name)}</strong><button type="button" data-logout>Log out</button></div></aside><div class="workspace"><header class="topbar"><div><span>Communications Department</span><strong>${escapeHtml(NAVIGATION.find(([key]) => key === active)?.[1] || "Desk")}</strong></div><time>${new Intl.DateTimeFormat("en-GB", { weekday: "short", day: "2-digit", month: "short" }).format(new Date())}</time></header>${crumbs}<main id="main">${content}</main><footer><span>SMCU · Internal system</span><span>Version 1.0</span></footer></div></div><div class="toast" role="status" aria-live="polite"></div>`;
}

export function renderLogin({ local, returnPath }) {
  return `<main class="auth-page" id="main"><section class="auth-card"><div class="auth-mark"><small>Standard Maintenance Company Uniform</small><strong>Communications Desk</strong></div><div class="auth-body"><span class="eyebrow">Private internal system</span><h1>Jamie’s Desk</h1><p>${local ? "Local development session. No password or credential is stored." : "Access must be provided by the configured Cloudflare authentication layer."}</p>${local ? `<button class="button" type="button" data-local-login data-return="${escapeHtml(returnPath)}">Continue as Jamie</button>` : `<a class="button" href="../unauthorised/">Access unavailable</a>`}<small>${local ? "Session ends when this browser tab closes or after eight hours." : "No production authentication provider is configured."}</small></div></section></main>`;
}
export function renderUnauthorised(route) { return `<main class="auth-page" id="main"><section class="auth-card"><div class="auth-mark"><small>SMCU</small><strong>Access denied</strong></div><div class="auth-body"><span class="eyebrow">Private internal system</span><h1>Unauthorised</h1><p>This Desk is available only to Jamie through the configured authentication provider.</p><a class="button" href="${route("login/index.html")}">Return to login</a></div></section></main>`; }

export function renderDashboard(view, route) {
  const { currentCampaign, progress, nextAction, queue, recentPublication, systems } = view;
  const next = currentCampaign ? `<a class="next-work" href="${route(`campaign/index.html?id=${encodeURIComponent(currentCampaign.id)}`)}"><span class="eyebrow">Today’s work</span><strong>${escapeHtml(nextAction?.label || "Campaign complete")}</strong><small>${escapeHtml(currentCampaign.id)} · ${escapeHtml(currentCampaign.title)} →</small></a>` : `<div class="next-work is-clear"><span class="eyebrow">Today’s work</span><strong>Nothing requires attention</strong><small>The Desk is clear.</small></div>`;
  const campaign = currentCampaign ? `<a class="current-campaign" href="${route(`campaign/index.html?id=${encodeURIComponent(currentCampaign.id)}`)}"><div><span class="eyebrow">Current campaign</span><code>${escapeHtml(currentCampaign.id)}</code><h2>${escapeHtml(currentCampaign.title)}</h2><p>Next: ${escapeHtml(nextAction?.label || "Complete")}</p></div><div class="single-progress"><strong>${progress.percentage}%</strong><progress class="progress" aria-label="Campaign progress" value="${progress.percentage}" max="100">${progress.percentage}%</progress><small>${progress.completed} of ${progress.total}</small></div></a>` : calmEmpty("No current campaign", "Campaign planning is clear.");
  const publication = recentPublication ? `<a class="recent-publication" href="${route(`document/index.html?id=${encodeURIComponent(recentPublication.id)}`)}"><div><span class="eyebrow">Recent publication</span><code>${escapeHtml(recentPublication.id)}</code><strong>${escapeHtml(recentPublication.title)}</strong></div><time datetime="${escapeHtml(recentPublication.publishDate)}">${formatDate(recentPublication.publishDate)}</time><span>→</span></a>` : calmEmpty("No recent publication", "Nothing has been published yet.");
  return `<section class="dashboard-intro"><div><span class="eyebrow">Jamie’s work desk</span><h1>What should I do next?</h1></div><div class="stamp">Controlled<small>Communications</small></div></section><section class="dashboard-grid"><div>${next}${campaign}</div><div><section class="queue-summary"><div class="section-heading"><span class="eyebrow">Publishing queue</span><a href="${route("publishing/index.html")}">Open queue →</a></div><div><a href="${route("publishing/index.html#ready")}"><strong>${queue.ready.length}</strong><span>Ready</span></a><a href="${route("publishing/index.html#blocked")}"><strong>${queue.blocked.length}</strong><span>Blocked</span></a><a href="${route("publishing/index.html#scheduled")}"><strong>${queue.scheduled.length}</strong><span>Scheduled</span></a></div></section>${publication}</div></section><section class="system-bar" aria-label="System status"><strong>System status</strong>${systems.map((system) => `<span><i class="${system.status === "Connected" ? "on" : "off"}"></i>${escapeHtml(system.label)} · ${escapeHtml(system.status)}</span>`).join("")}</section>`;
}

export function renderCommunications(repository, counts, assetHealth) {
  const registers = repository.sections.map((section) => `<a href="../register/index.html?section=${encodeURIComponent(section.slug)}"><code>${escapeHtml(section.code)}</code><strong>${escapeHtml(section.title)}</strong><span>${counts[section.slug] || 0}</span></a>`).join("");
  return `<section class="page-head"><div><span class="eyebrow">Content and artwork</span><h1>Communications</h1><p>Write, find, review and prepare communications for publishing.</p></div></section><section class="page-section"><div class="section-heading"><div><span class="eyebrow">Search</span><h2>Communication records</h2></div></div><div data-search-mount></div><div class="result-count" data-results-summary aria-live="polite"></div><div class="record-list" data-results></div><details class="utility-drawer"><summary>Registers <span>Document series</span></summary><div class="register-list">${registers}</div></details></section><section class="page-section artwork-section"><div class="section-heading"><div><span class="eyebrow">Artwork</span><h2>Asset Library</h2></div><span>${assetHealth.total} assets · ${assetHealth.needsArtwork} needed</span></div><details class="utility-drawer" data-artwork-drawer><summary>Browse artwork <span>Purpose, usage and files</span></summary><div data-asset-controls></div><div class="result-count" data-asset-summary aria-live="polite"></div><div class="asset-list" data-asset-results></div></details></section>`;
}
export function renderSearchControls(options, prefix) { const opts = (items) => items.map((item) => `<option value="${escapeHtml(item)}">${escapeHtml(item)}</option>`).join(""); return `<form class="search-form" data-search-form role="search"><label class="wide"><span>Search</span><input id="${prefix}-query" name="query" type="search" placeholder="ID, title, summary, tag or author"></label><label><span>Status</span><select name="status"><option value="">All statuses</option>${opts(options.statuses)}</select></label><label><span>Type</span><select name="type"><option value="">All types</option>${opts(options.types)}</select></label><details><summary>More filters</summary><div><label><span>Department</span><select name="department"><option value="">All departments</option>${opts(options.departments)}</select></label><label><span>Year</span><select name="year"><option value="">All years</option>${opts(options.years)}</select></label></div></details><button class="button secondary" type="reset">Clear</button></form>`; }
export function renderRecordList(documents, href) { return documents.length ? documents.map((document) => `<a class="record-row" href="${href(document)}"><code>${escapeHtml(document.id)}</code><div><strong>${escapeHtml(document.title)}</strong><small>${escapeHtml(document.summary)}</small></div>${statusChip(document.status)}<time>${formatDate(document.modifiedDate)}</time><span>→</span></a>`).join("") : calmEmpty("No communications found", "Adjust the search or filters."); }
export function renderRegister(section, documents, href) { return `<section class="page-head compact"><div><span class="eyebrow">${escapeHtml(section.code)} register</span><h1>${escapeHtml(section.title)}</h1><p>${escapeHtml(section.description)}</p></div></section><section class="page-section"><div class="record-list">${documents.length ? renderRecordList(documents, href) : calmEmpty("Register clear", "No communications filed.")}</div></section>`; }

export function renderAssetControls(options) { const opts = (items) => items.map((item) => typeof item === "string" ? `<option value="${escapeHtml(item)}">${escapeHtml(item)}</option>` : `<option value="${escapeHtml(item.value)}">${escapeHtml(item.label)}</option>`).join(""); return `<form class="search-form asset-search" data-asset-search role="search"><label class="wide"><span>Search artwork</span><input name="query" type="search" placeholder="Filename, title, communication or campaign"></label><label><span>Status</span><select name="status"><option value="">All statuses</option>${opts(options.statuses)}</select></label><label><span>Campaign</span><select name="campaign"><option value="">All campaigns</option>${opts(options.campaigns)}</select></label><details><summary>More filters</summary><div><label><span>Communication</span><select name="communication"><option value="">All communications</option>${opts(options.communications)}</select></label><label><span>Category</span><select name="category"><option value="">All categories</option>${opts(options.categories)}</select></label><label><span>Orientation</span><select name="orientation"><option value="">All orientations</option>${opts(options.orientations)}</select></label><label><span>Format</span><select name="format"><option value="">All formats</option>${opts(options.formats)}</select></label></div></details><button class="button secondary" type="reset">Clear</button><button class="button" type="button" data-copy-library>Copy all URLs</button></form>`; }
export function renderAssetCards(views, route) { return views.length ? views.map(({ asset, usage }) => `<article class="asset-row"><a href="${route(`asset/index.html?id=${encodeURIComponent(asset.id)}`)}"><img src="${escapeHtml(asset.url)}" alt="${escapeHtml(asset.altText)}"></a><div><code>${escapeHtml(asset.id)}</code><h3><a href="${route(`asset/index.html?id=${encodeURIComponent(asset.id)}`)}">${escapeHtml(asset.title)}</a></h3><p>${escapeHtml(asset.type)} · ${asset.dimensions.width} × ${asset.dimensions.height} · ${usage.count} links</p></div>${statusChip(asset.status)}<button class="button secondary" type="button" data-copy-url="${escapeHtml(asset.url)}" type="button">Copy URL</button></article>`).join("") : calmEmpty("No artwork found", "Adjust the artwork search."); }

export function renderCommunication(document, campaignContext, readiness, route) {
  const metadata = [["Department", document.department], ["Owner", document.author], ["Type", document.documentType], ["Created", formatDate(document.createdDate)], ["Modified", formatDate(document.modifiedDate)], ["Publish date", formatDate(document.publishDate)]];
  const assets=document.assets||[];
  return `<article><header class="workspace-head"><div><span class="eyebrow">Communication</span><div class="title-line"><h1>${escapeHtml(document.id)}</h1>${statusChip(document.status)}</div><h2>${escapeHtml(document.title)}</h2></div><a class="button" href="#artwork">Upload artwork</a></header>${campaignContext}<section class="page-section communication-content"><div><span class="eyebrow">Content</span><h2>${escapeHtml(document.title)}</h2><p>${escapeHtml(document.summary)}</p></div><details class="utility-drawer"><summary>Metadata <span>Document record</span></summary><dl class="metadata-grid">${metadata.map(([label, value]) => `<div><dt>${label}</dt><dd>${escapeHtml(value)}</dd></div>`).join("")}</dl></details></section><section class="page-section" id="artwork"><div class="section-heading"><div><span class="eyebrow">Artwork</span><h2>Communication artwork</h2></div><button class="button secondary" type="button" data-copy-all>Copy all URLs</button></div><div class="artwork-upload" data-dropzone tabindex="0" role="button" aria-label="Upload artwork by selecting files or dropping them here"><input data-upload-input type="file" accept="image/png,image/jpeg,image/webp" multiple hidden><strong>Upload artwork</strong><span>Drop PNG, JPEG or WebP files here, or select files</span><button class="button" type="button" data-choose-files>Select files</button><progress data-upload-progress max="100" value="0" hidden>0%</progress><p data-upload-status role="status" aria-live="polite"></p></div><div class="communication-assets managed-assets">${assets.length?assets.map(assetCard).join(""):`<p class="lane-empty">No artwork uploaded.</p>`}</div></section><section class="page-section readiness"><div><span class="eyebrow">Publishing readiness</span><h2>${escapeHtml(readiness.label)}</h2>${readiness.reasons.length ? `<ul>${readiness.reasons.map(reason => `<li>${escapeHtml(reason)}</li>`).join("")}</ul>` : `<p>Content and artwork are ready.</p>`}</div><a class="button${readiness.lane !== "ready" ? " disabled" : ""}" href="${route(`publishing/index.html#${readiness.lane}`)}">${readiness.lane === "ready" ? "Publish" : "Open Publishing"}</a></section><details class="page-section utility-drawer"><summary>History <span>${document.history.length} events</span></summary>${timeline(document.history)}</details></article><dialog class="preview-dialog" aria-labelledby="preview-title"><header><strong id="preview-title">Artwork preview</strong><button type="button" aria-label="Close preview">&times;</button></header><img src="" alt=""></dialog>`;
}
export function renderCommunicationCampaign(campaign, progress, phase, route) { return campaign ? `<aside class="linked-campaign"><span>Campaign</span><a href="${route(`campaign/index.html?id=${encodeURIComponent(campaign.id)}`)}"><code>${escapeHtml(campaign.id)}</code><strong>${escapeHtml(campaign.title)}</strong></a><span>Phase</span><strong>${escapeHtml(phase)}</strong><span>Progress</span><strong>${progress.percentage}%</strong></aside>` : ""; }

export function renderCampaigns(views, route) { return `<section class="page-head"><div><span class="eyebrow">Planning</span><h1>Campaigns</h1><p>Plan communications and move them toward publishing.</p></div></section><section class="page-section"><div class="campaign-list">${views.length ? views.map((view) => campaignCard(view, route)).join("") : calmEmpty("No current campaigns", "Nothing is being planned.")}</div></section>`; }
export function renderCampaign(view, route) { const { campaign, progress, nextAction, communications } = view; return `<article><header class="workspace-head"><div><span class="eyebrow">Campaign</span><div class="title-line"><h1>${escapeHtml(campaign.id)}</h1>${statusChip(campaign.status)}</div><h2>${escapeHtml(campaign.title)}</h2></div><div class="next-action"><span>Next action</span><strong>${escapeHtml(nextAction?.label || "Complete")}</strong></div></header><section class="page-section campaign-overview"><div><span class="eyebrow">Plan</span><p>${escapeHtml(campaign.description)}</p><dl class="metadata-grid"><div><dt>Owner</dt><dd>${escapeHtml(campaign.owner)}</dd></div><div><dt>Start</dt><dd>${formatDate(campaign.startDate)}</dd></div><div><dt>Target</dt><dd>${formatDate(campaign.targetPublishDate)}</dd></div></dl></div><div class="single-progress"><strong>${progress.percentage}%</strong><progress class="progress" aria-label="Campaign progress" value="${progress.percentage}" max="100">${progress.percentage}%</progress><small>${progress.completed} of ${progress.total}</small></div></section><section class="page-section"><div class="section-heading"><div><span class="eyebrow">Communications</span><h2>Linked work</h2></div></div><div class="record-list">${communications.map((document) => `<a class="record-row simple" href="${route(`document/index.html?id=${encodeURIComponent(document.id)}`)}"><code>${escapeHtml(document.id)}</code><strong>${escapeHtml(document.title)}</strong>${statusChip(document.status)}<span>→</span></a>`).join("")}</div></section><section class="page-section"><div class="section-heading"><div><span class="eyebrow">Checklist</span><h2>What remains</h2></div></div><ol class="checklist">${campaign.checklist.map((item) => `<li class="${item.completed ? "done" : ""}"><span>${item.completed ? "✓" : ""}</span><strong>${escapeHtml(item.label)}</strong></li>`).join("")}</ol></section><section class="page-section readiness"><div><span class="eyebrow">Publishing overview</span><h2>${escapeHtml(nextAction?.label || "Campaign complete")}</h2><p>Target publication: ${formatDate(campaign.targetPublishDate)}</p></div><a class="button" href="${route("publishing/index.html")}">Open Publishing</a></section></article>`; }

export function renderPublishing(queue, route) { const lane = (key, title, copy) => `<section class="publishing-lane" id="${key}"><div class="section-heading"><div><span class="eyebrow">${title}</span><h2>${queue[key].length}</h2></div><p>${copy}</p></div><div>${queue[key].length ? queue[key].map(({ document, readiness }) => publishingRow(document, readiness, route)).join("") : `<p class="lane-empty">None.</p>`}</div></section>`; return `<section class="page-head"><div><span class="eyebrow">Operational centre</span><h1>Publishing</h1><p>One queue. Every communication explains what happens next.</p></div></section><div class="publishing-board">${lane("ready", "Ready", "Content and artwork confirmed.")}${lane("blocked", "Blocked", "Work or service configuration is missing.")}${lane("scheduled", "Scheduled", "Waiting for its publication time.")}${lane("published", "Published", "Recently completed publications.")}</div><dialog class="publish-dialog" aria-labelledby="publish-title"><form method="dialog"><header><div><span class="eyebrow">Confirm publication</span><h2 id="publish-title">Choose destinations</h2></div><button value="cancel" aria-label="Close publishing confirmation">&times;</button></header><div class="publish-form"><p data-publish-summary></p><fieldset><legend>Destinations</legend><label><input type="checkbox" name="destination" value="shopify"> Shopify</label><label><input type="checkbox" name="destination" value="instagram"> Instagram via Buffer</label><label><input type="checkbox" name="destination" value="facebook"> Facebook via Buffer</label></fieldset><label><span>Action</span><select name="action"><option value="publish">Publish / add to queue</option><option value="schedule">Schedule</option><option value="draft">Shopify draft</option></select></label><label data-schedule hidden><span>Schedule time</span><input name="scheduledTime" type="datetime-local"></label><div class="publish-result" data-publish-result role="status" aria-live="polite"></div><div class="dialog-actions"><button class="button secondary" value="cancel">Cancel</button><button class="button" type="button" data-confirm-publish>Review and confirm</button></div></div></form></dialog>`; }

export function renderSettings(systems, session, provider) { return `<section class="page-head"><div><span class="eyebrow">Configuration</span><h1>Settings</h1><p>Operator and future service connections.</p></div></section><section class="page-section settings"><div class="profile"><span class="eyebrow">Operator profile</span><strong>${escapeHtml(session.operator.name)}</strong><p>Single administrator · ${escapeHtml(provider.label)}</p></div><div class="service-list">${systems.map((system) => `<div><span class="service-state ${system.status === "Connected" ? "connected" : "disconnected"}"></span><strong>${escapeHtml(system.label)}</strong><span>${escapeHtml(system.status)}</span><small>${escapeHtml(system.note)}</small></div>`).join("")}</div></section>`; }

export function renderAssetDetail(asset, usage, route) { return `<article><header class="workspace-head"><div><span class="eyebrow">Artwork</span><div class="title-line"><h1>${escapeHtml(asset.id)}</h1>${statusChip(asset.status)}</div><h2>${escapeHtml(asset.title)}</h2></div><a class="button" href="${escapeHtml(asset.url)}" target="_blank" rel="noopener">Open asset ↗</a></header><section class="asset-detail"><img src="${escapeHtml(asset.url)}" alt="${escapeHtml(asset.altText)}"><div><p>${escapeHtml(asset.description)}</p><dl class="metadata-grid"><div><dt>Filename</dt><dd>${escapeHtml(asset.filename)}</dd></div><div><dt>Dimensions</dt><dd>${asset.dimensions.width} × ${asset.dimensions.height}</dd></div><div><dt>Format</dt><dd>${escapeHtml(asset.format)}</dd></div><div><dt>Usage</dt><dd>${usage.count} links</dd></div></dl><div class="action-stack"><button class="button secondary" type="button" data-copy-url="${escapeHtml(asset.url)}">Copy URL</button><button class="button secondary" type="button" data-copy-markdown="${escapeHtml(asset.url)}" data-alt="${escapeHtml(asset.altText)}">Copy Markdown</button><button class="button secondary" type="button" data-copy-html="${escapeHtml(asset.url)}" data-alt="${escapeHtml(asset.altText)}">Copy HTML</button>${asset.communication ? `<a class="button secondary" href="${route(`document/index.html?id=${encodeURIComponent(asset.communication)}`)}">Communication →</a>` : ""}${asset.campaign ? `<a class="button secondary" href="${route(`campaign/index.html?id=${encodeURIComponent(asset.campaign)}`)}">Campaign →</a>` : ""}</div></div></section></article>`; }
export function renderError(message) { return `<main class="auth-page" id="main"><section class="auth-card"><div class="auth-body"><span class="eyebrow">System error</span><h1>Desk unavailable</h1><p>${escapeHtml(message)}</p></div></section></main>`; }

function assetCard(asset) { const alt=asset.altText??asset.alt??""; const size=asset.size?`${(asset.size/1024/1024).toFixed(2)} MB`:"Size unavailable"; const managed=asset.storageKind!=="legacy"; const primary=Boolean(asset.primary); return `<article class="communication-asset managed-asset${primary?" is-primary":""}" data-asset-id="${escapeHtml(asset.id)}"><div class="asset-visual"><button class="preview" type="button" aria-label="Preview ${escapeHtml(asset.filename)}" data-preview="${escapeHtml(asset.url)}" data-alt="${escapeHtml(alt)}"><img src="${escapeHtml(asset.url)}" alt="${escapeHtml(alt)}"></button>${primary?`<strong class="primary-flag">Primary artwork</strong>`:""}</div><div class="asset-info"><header class="asset-heading"><div><strong title="${escapeHtml(asset.filename)}">${escapeHtml(asset.filename)}</strong><span>${asset.width} &times; ${asset.height} &middot; ${escapeHtml(asset.mimeType||"")} &middot; ${size}</span></div><code>${escapeHtml(asset.id)}</code></header><div class="asset-url"><code title="${escapeHtml(asset.url)}">${escapeHtml(asset.url)}</code><div class="asset-copy-actions" aria-label="Copy artwork link"><a href="${escapeHtml(asset.url)}" target="_blank" rel="noopener">Open</a><button type="button" data-copy-url="${escapeHtml(asset.url)}">URL</button><button type="button" data-copy-markdown="${escapeHtml(asset.url)}" data-alt="${escapeHtml(alt)}">Markdown</button><button type="button" data-copy-html="${escapeHtml(asset.url)}" data-alt="${escapeHtml(alt)}">HTML</button></div></div><label class="alt-field${alt.trim()?"":" is-missing"}"><span>Alt text${alt.trim()?"":" — required"}</span><div><input data-alt-input value="${escapeHtml(alt)}" maxlength="500" ${managed?"":"readonly"} aria-label="Alt text for ${escapeHtml(asset.filename)}">${managed?`<button type="button" data-save-alt>Save</button>`:""}</div></label><div class="asset-management" aria-label="Manage ${escapeHtml(asset.filename)}">${managed?`<button type="button" data-primary ${primary?"disabled aria-current=\"true\"":""}>${primary?"Primary":"Set primary"}</button><span class="reorder-actions"><button type="button" data-move="up" aria-label="Move ${escapeHtml(asset.filename)} earlier">&uarr;</button><button type="button" data-move="down" aria-label="Move ${escapeHtml(asset.filename)} later">&darr;</button></span><label class="replace-label"><span>Replace</span><input class="visually-hidden" type="file" data-replace accept="image/png,image/jpeg,image/webp" aria-label="Replace ${escapeHtml(asset.filename)}"></label><button class="danger-action" type="button" data-delete>Delete</button>`:`<span class="legacy-note">Permanent legacy artwork</span>`}</div></div></article>`; }
function campaignCard({ campaign, progress, nextAction, communications }, route) { return `<a class="campaign-card" href="${route(`campaign/index.html?id=${encodeURIComponent(campaign.id)}`)}"><div><code>${escapeHtml(campaign.id)}</code>${statusChip(campaign.status)}</div><h2>${escapeHtml(campaign.title)}</h2><p>Next: ${escapeHtml(nextAction?.label || "Complete")}</p><progress class="progress" aria-label="Campaign progress" value="${progress.percentage}" max="100">${progress.percentage}%</progress><small>${progress.percentage}% · ${communications.length} communications · Target ${formatDate(campaign.targetPublishDate)}</small></a>`; }
function publishingRow(document, readiness, route) { return `<article class="publishing-row"><div><code>${escapeHtml(document.id)}</code><strong>${escapeHtml(document.title)}</strong></div><div>${readiness.reasons.length ? `<ul>${readiness.reasons.map((reason) => `<li>${escapeHtml(reason)}</li>`).join("")}</ul>` : `<span>${escapeHtml(readiness.label)}</span>`}</div>${readiness.action ? `<button class="publish-button" type="button" data-publish="${escapeHtml(document.id)}" data-modified="${escapeHtml(document.modifiedDate)}" data-title="${escapeHtml(document.title)}">Publish</button>` : `<a href="${route(`document/index.html?id=${encodeURIComponent(document.id)}`)}">Open →</a>`}</article>`; }
function timeline(items) { return `<ol class="timeline">${[...items].sort((a, b) => b.date.localeCompare(a.date)).map((item) => `<li><time>${formatDate(item.date)}</time><div><strong>${escapeHtml(item.action)}</strong><p>${escapeHtml(item.note)}</p></div></li>`).join("")}</ol>`; }
function calmEmpty(title, text) { return `<div class="empty"><strong>${escapeHtml(title)}</strong><p>${escapeHtml(text)}</p></div>`; }
